#!/usr/bin/env bash
# In this first task you need to configure web-02 to be identical to web-01. Fortunat>sudo apt-get -y update
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World' > /var/www/html/index.html
