#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.                                         
sudo apt -y update
sudo apt -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo 'Hello World' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v\=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
