#!/usr/bin/env bash
# In this first task you need to configure web-02 to be identical to web-01. Fortunately, you built a Bash script during your web server project, and they’ll now come in handy to easily configure web-02.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "12i add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
