#!/usr/bin/env bash
# In this first task you need to configure web-02 to be identical to web-01. Fortunat>sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "12i add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
