#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
echo "frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 3514-web-01 35.237.215.97:80 check
   server 3514-web-02 3.94.163.153:80 check" | sudo tee --append /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
