#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo "frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 3514-web-01 34.75.84.58:80 check
    server 3514-web-02 34.138.236.20:80 check" | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart
