#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80.
apt-get -y update
apt-get -y install nginx
service nginx start 
sudo sed -i '22s/.*/\t\tlisten 80 default_server/g' /etc/nginx/sites-enabled/default
sudo sed -i '23s/.*/\t\tlisten [::]:80 default_serverr/g' /etc/nginx/sites-enabled/default
sudo service nginx restart