#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80.
apt-get -y update
apt-get -y install nginx
service nginx start 
sudo sed -i 's/sites-enabled/sites-availabe' /etc/nginx/nginx.conf
sudo service nginx restart