#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80. 
sed -i "s/sites-enabled/sites-availabe" /etc/nginx/nginx.conf
service nginx restart